Hw06 email
ApolinarySzumski/nodejs-homeworks pull request #5
Opened 2024-07-12 11:59 UTC by ApolinarySzumski

Hej, zrobiłem niezbędną część 6 zadania, proszę o sprawdzenie. Pytanko czy często Postman ma problemy? Spędziłem 1,5h na szukaniu błędu, którego nie ma jedyne co musiałem zrobić to zresetować Postmana, czuję ulgę, ale szukanie to był horror. Pozdrawiam!

2024-07-12 16:46 UTC, KamilMr commented
> Hej, zrobiłem niezbędną część 6 zadania, proszę o sprawdzenie. Pytanko czy często Postman ma problemy? Spędziłem 1,5h na szukaniu błędu, którego nie ma jedyne co musiałem zrobić to zresetować Postmana, czuję ulgę, ale szukanie to był horror. Pozdrawiam!

Ja rzadko mam problem z postmanem, jego minus to to, że musi mieć dostep do internetu.

2024-07-12 16:58 UTC, KamilMr requested changes
Na lms filmik z instrukcją co poprawic :)

2024-07-12 16:58 UTC, KamilMr commented on controller/user.js
> +      html: `<h1>Your link to verificate email: ${verificationEmailToken}</h1>`,
```suggestion
      html: `<h1>Your link to verificate email: ${verificationEmailToken}</h1>`,
```
Tu jakiś ładny html na przyszłość :) tak aby był button albo <a> tag.

2024-07-16 12:05 UTC, ApolinarySzumski commented on controller/user.js
> +      html: `<h1>Your link to verificate email: ${verificationEmailToken}</h1>`,
+

2024-07-16 12:08 UTC, ApolinarySzumski commented on controller/user.js
> +      html: `<h1>Your link to verificate email: ${verificationEmailToken}</h1>`,
Starałem się ogarnąć wszystkie rzeczy wymienione w filmiku, testowałem postmanem zobaczymy czy wystarczająco dobrze :))

2024-07-17 12:14 UTC, KamilMr approved these changes

2024-07-17 12:14 UTC, KamilMr commented on controller/user.js
> +    const emailHTML = `<a href="http://localhost:3000">Click here: ${verificationEmailToken}</a>`;
```suggestion
    const emailHTML = `<a href="http://localhost:3000/${verificationEmailToken}">Click here</a>`;
```

2024-07-17 12:14 UTC, KamilMr commented on controller/user.js
> +    const emailHTML = `<a href="http://localhost:3000">Your link to verificate email: ${user.verificationToken}</a>`;
```suggestion
    const emailHTML = `<a href="http://localhost:3000/${user.verificationToken}">Your link to verificate email</a>`;
```

2024-07-17 12:14 UTC, KamilMr commented on controller/user.js
> +    sendEmail(EMAIL, EMAIL, emailSubject, emailText, emailHTML);
Zrób z tego asynchroniczną z uzyciem await i kedy bedzie błąd przy wysyłce email to powiedz do fe że nastąpił błąd i email nie wyslano.

2024-07-17 12:14 UTC, KamilMr commented on controller/user.js
> +    const verificationEmail = sendEmail(
Z tego co widzę to sendEmail nic nie zwraca :)

2024-07-17 12:14 UTC, KamilMr commented on controller/user.js
> +const EMAIL = "apolinary@poczta.onet.pl";
Zastanawiam się czy nie lepiej to dać do .env? Twój adress prywatny. I można go łatwiej zmienić jak już będzie w .env

2024-07-17 12:58 UTC, ApolinarySzumski commented on controller/user.js
> +const EMAIL = "apolinary@poczta.onet.pl";
racja, nie pomyślałem :)

2024-07-17 13:00 UTC, ApolinarySzumski commented on controller/user.js
> +    const emailHTML = `<a href="http://localhost:3000">Click here: ${verificationEmailToken}</a>`;
widziałem milion razy na stronach, ale sam nie wprowadziłem :D

2024-07-17 13:01 UTC, ApolinarySzumski commented on controller/user.js
> +    const emailHTML = `<a href="http://localhost:3000">Your link to verificate email: ${user.verificationToken}</a>`;
+

2024-07-17 13:12 UTC, ApolinarySzumski commented on controller/user.js
> +    const verificationEmail = sendEmail(
No tak, to relikt przeszłości co tu zostało :)

2024-07-17 13:28 UTC, merged